# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    pwd
    ls
  displayName: 'Get bearings'

- script: |
    ./mvnw package
  displayName: 'Build Jar'

- script: docker build -t springio/gs-spring-boot-docker .
  displayName: 'Build Docker Image'

- script: |
    docker login kylers.azurecr.io -u $(acr-user) -p $(acr-pass)
    docker tag springio/gs-spring-boot-docker kylers.azurecr.io/springio/gs-spring-boot-docker
    docker push kylers.azurecr.io/springio/spring-test